# ###############################
# Main config file for MkDocs.
# ###############################
#
# To run:
# mkdocs serve
# More help: https://www.holunda.io/camunda-bpm-taskpool/developer-guide/project-setup.html#build-documentation
# ###############################

site_name: Camunda BPM Data
site_url: https://www.holunda.io/camunda-bpm-data/
site_author: Holisticon BPM Craftsman
site_description: >-
  Beautiful process data handling for Camunda BPM.

copyright: Copyright &copy; 2016 - 2022, Holisticon AG

use_directory_urls: false

# Repository
repo_name: holunda-io/camunda-bpm-data
repo_url: https://github.com/holunda-io/camunda-bpm-data/
edit_uri: edit/develop/docs/

markdown_extensions:
    - attr_list
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition


theme:
  name: material
  features:
    - navigation.instant # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.tabs # add top level nav items into a horizontal menu
    - navigation.tabs.sticky # make horizontal menu sticky (insider feature)
    - navigation.sections
    - navigation.top # add "navigate to top" page icon on bottom left
    - toc.integrate # integrate site TOC into the menu on the left
  logo: assets/img/camunda-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css: [ assets/css/extra.css ]

extra:
  social:
    - icon: fontawesome/brands/twitter
      name: Holisticon on Twitter
      link: https://twitter.com/holisticon
    - icon: fontawesome/brands/medium
      name: Holisticon BPM Craftsmen on Medium
      link: https://medium.com/holisticon-consultants/tagged/mpb
  version:
    provider: mike

plugins:
  - search
#  - git-committers:
#      repository: holunda-io/camunda-bpm-taskpool
#      branch: master
#      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css                    # the directory to put the version selector's CSS
      javascript_dir: js            # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                                            # uses the version specified via `mike deploy`
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - User Guide:
      - Motivation: user-guide/motivation.md
      - Features: user-guide/features.md
      - Further Outlook: user-guide/further-outlook.md
  - Examples:
      - Usage in Java: user-guide/examples-java.md
      - Usage in Kotlin: user-guide/examples-kotlin.md
      - Usage without Camunda Platform: user-guide/examples-no-engine.md
  - Developer Guide:
      - Contributing: developer-guide/contribution.md
      - Project Setup: developer-guide/project-setup.md
